/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for rk_ecdsasignature
 */
#include <linux/asn1_ber_bytecode.h>
#include "rk_ecdsasignature.asn1.h"

enum rk_ecdsasignature_actions {
	ACT_rk_ecc_get_signature_r = 0,
	ACT_rk_ecc_get_signature_s = 1,
	NR__rk_ecdsasignature_actions = 2
};

static const asn1_action_t rk_ecdsasignature_action_table[NR__rk_ecdsasignature_actions] = {
	[   0] = rk_ecc_get_signature_r,
	[   1] = rk_ecc_get_signature_s,
};

static const unsigned char rk_ecdsasignature_machine[] = {
	// ECDSASignature
	[   0] = ASN1_OP_MATCH,
	[   1] = _tag(UNIV, CONS, SEQ),
	[   2] =  ASN1_OP_MATCH_ACT,		// x
	[   3] =  _tag(UNIV, PRIM, INT),
	[   4] =  _action(ACT_rk_ecc_get_signature_r),
	[   5] =  ASN1_OP_MATCH_ACT,		// y
	[   6] =  _tag(UNIV, PRIM, INT),
	[   7] =  _action(ACT_rk_ecc_get_signature_s),
	[   8] = ASN1_OP_END_SEQ,
	[   9] = ASN1_OP_COMPLETE,
};

const struct asn1_decoder rk_ecdsasignature_decoder = {
	.machine = rk_ecdsasignature_machine,
	.machlen = sizeof(rk_ecdsasignature_machine),
	.actions = rk_ecdsasignature_action_table,
};
